# Generated by Django 4.1.6 on 2023-02-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('sport', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
